### ISSUE TITLE
Tracking issue: Flaky/broken builds

### ISSUE THREAD

**Issue by JamesGuthrie** [timescale/promscale_extension#385]
If you come across a flaky test or broken build (GitHub issue) please open an issue for it and link it here.

**Comment by JamesGuthrie** [comment]
This [build](https://github.com/timescale/promscale_extension/runs/7209617714?check_suite_focus=true) has a flaky test:

```
--- FAIL: TestCompareTraceQueryResponse (1.75s)
    trace_query_integration_test.go:269: 
        	Error Trace:	trace_query_integration_test.go:269
        	            				trace_query_integration_test.go:113
        	            				main_test.go:237
        	            				postgres_container.go:190
        	            				main_test.go:201
        	            				main_test.go:196
        	            				trace_query_integration_test.go:82
        	Error:      	Received unexpected error:
        	            	http get: Get "http://localhost:9201/api/services": dial tcp [::1]:9201: connect: connection refused
        	Test:       	TestCompareTraceQueryResponse
```

**Comment by JamesGuthrie** [comment]
This [build](https://github.com/timescale/promscale/runs/7449822834?check_suite_focus=true) has a flaky test `TestExemplarQueryEndpoint`

```
--- FAIL: TestExemplarQueryEndpoint (2.05s)
    --- FAIL: TestExemplarQueryEndpoint/test_exemplars_query_endpoint (0.02s)
        promql_endpoint_integration_test.go:234: binary expr 1 (exempar query, [start to start+30] query=metric_1 + metric_1) gives unexpected response:
            timescale
            {"status":"success","data":[{"seriesLabels":{"__name__":"metric_1","aaa":"000","foo":"bar","instance":"1"},"exemplars":[{"labels":{"component":"some_component","label_extra":"X"},"value":"9","timestamp":1658408857.985},{"labels":{"TraceID":"some_trace_id","label_extra":"X"},"value":"51","timestamp":1658408887.985}]},{"seriesLabels":{"__name__":"metric_1","foo":"bar","instance":"3"},"exemplars":[{"labels":{"TraceID":"some_trace_id","job":"some_job","label_extra":"X"},"value":"85","timestamp":1658408857.985},{"labels":{"TraceID":"some_trace_id","job":"some_job","label_extra":"X"},"value":"85","timestamp":1658408887.985}]}]}
            prom
            {"status":"success","data":[{"seriesLabels":{"__name__":"metric_1","aaa":"000","foo":"bar","instance":"1"},"exemplars":[{"labels":{"component":"some_component","label_extra":"X"},"value":"9","timestamp":1658408857.985},{"labels":{"TraceID":"some_trace_id","label_extra":"X"},"value":"51","timestamp":1658408887.985}]},{"seriesLabels":{"__name__":"metric_1","foo":"bar","instance":"3"},"exemplars":[{"labels":{"TraceID":"some_trace_id","job":"some_job","label_extra":"X"},"value":"85","timestamp":1658408857.985}]}]}
```

**Comment by JamesGuthrie** [comment]
This [build](https://github.com/timescale/promscale/runs/7339461764?check_suite_focus=true) has a flaky test:

```
--- FAIL: TestContinuousAggDataRetention (2.18s)
    continuous_agg_test.go:396: 
        	Error Trace:	continuous_agg_test.go:396
        	            				main_test.go:237
        	            				postgres_container.go:190
        	            				main_test.go:201
        	            				main_test.go:196
        	            				continuous_agg_test.go:344
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 3
        	Test:       	TestContinuousAggDataRetention
        	Messages:   	Expected for cagg to have exactly 2 chunks
```

**Comment by JamesGuthrie** [comment]
This [build](https://github.com/timescale/promscale/runs/7357971960?check_suite_focus=true) has a flaky test `TestMigrateLock`:

```
--- FAIL: TestMigrateLock (1.56s)
    migrate_test.go:112: Could not acquire migration lock. Ensure there are no other connectors running and try again.

```

**Comment by JamesGuthrie** [comment]
This [build](https://github.com/timescale/promscale_extension/runs/8005227965?check_suite_focus=true) shows a new kind of flakiness w.r.t. connecting to the database from the extension's sql tests: 

```
running 12 tests
test sql_tests_testdata_create_ingest_temp_table_sql ... ok
test sql_tests_testdata_defaults_sql ... ok
test sql_tests_testdata_drop_metric_sql ... ok
test sql_tests_testdata_info_view_sql ... ok
test sql_tests_testdata_large_tracing_tags_support_sql ... ok
test sql_tests_testdata_metric_chunk_interval_sql ... ok
test sql_tests_testdata_metric_retention_sql ... ok
test sql_tests_testdata_ps_trace_delete_all_traces_sql ... ok
test sql_tests_testdata_support_sql ... ok
test sql_tests_testdata_tag_map_sql ... FAILED
test sql_tests_testdata_views_sql ... ok
test sql_tests_testdata_trace_compression_sql ... ok

failures:

---- sql_tests_testdata_tag_map_sql stdout ----
thread 'sql_tests_testdata_tag_map_sql' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', test-common/src/postgres_container/mod.rs:74:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    sql_tests_testdata_tag_map_sql

test result: FAILED. 11 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 32.93s
```

**Comment by jgpruitt** [comment]
The first attempt failed. The second attempt worked.

```
failures:

---- sql_tests_testdata_tag_map_sql stdout ----
thread 'sql_tests_testdata_tag_map_sql' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', test-common/src/postgres_container/mod.rs:74:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    sql_tests_testdata_tag_map_sql

test result: FAILED. 11 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 32.93s

error: test failed, to rerun pass '-p sql-tests --test tests'
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 101
```


https://github.com/timescale/promscale_extension/actions/runs/2922645986/attempts/1

**Comment by jgpruitt** [comment]
saw a string of these
```
---- upgrade_first_no_data_test stdout ----
thread 'upgrade_first_no_data_test' panicked at 'failed to start container', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/testcontainers-0.14.0/src/clients/cli.rs:48:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- upgrade_first_with_data_test stdout ----
thread 'upgrade_first_with_data_test' panicked at 'failed to start container', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/testcontainers-0.14.0/src/clients/cli.rs:48:9
```

**Comment by jgpruitt** [comment]
https://github.com/timescale/promscale_extension/actions/runs/3062018914/jobs/4942499643

```
---- upgrade_prior_no_data_test stdout ----
thread 'upgrade_prior_no_data_test' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: Io, cause: Some(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }) }', test-common/src/postgres_container/mod.rs:74:58
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by JamesGuthrie** [comment]
I've opened https://github.com/timescale/promscale_extension/pull/518 in an attempt to address the issue with the tests failing with `Connection reset by peer`. If I'm being honest, it's more of a shot in the dark, because I don't understand what the circumstances are which lead to the connection reset. The PR assumes that it's transient, and recoverable.

**Comment by vonCorax** [comment]
I've encountered `fatal error: 'libintl.h' file not found` building promscale_extension for PostgreSQL 14.5 on FreeBSD 13.1. I've opened issue #532.

**Comment by jgpruitt** [comment]
sigh. 

https://github.com/timescale/promscale_extension/actions/runs/3388034141/jobs/5629523920

```
---- upgrade_prior_with_data_test stdout ----
thread 'upgrade_prior_with_data_test' panicked at 'failed to install the extension: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E23505), message: "duplicate key value violates unique constraint \"pg_extension_name_index\"", detail: Some("Key (extname)=(promscale) already exists."), hint: None, position: None, where_: None, schema: Some("pg_catalog"), table: Some("pg_extension"), column: None, datatype: None, constraint: Some("pg_extension_name_index"), file: Some("nbtinsert.c"), line: Some(563), routine: Some("_bt_check_unique") }) }', e2e/tests/upgrade-test.rs:623:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by jgpruitt** [comment]
https://github.com/timescale/promscale_extension/actions/runs/3651985342/jobs/6169840741

```
---- upgrade_prior_with_data_test stdout ----
thread 'upgrade_prior_with_data_test' panicked at 'failed to install the extension: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E23505), message: "duplicate key value violates unique constraint \"pg_extension_name_index\"", detail: Some("Key (extname)=(promscale) already exists."), hint: None, position: None, where_: None, schema: Some("pg_catalog"), table: Some("pg_extension"), column: None, datatype: None, constraint: Some("pg_extension_name_index"), file: Some("nbtinsert.c"), line: Some(663), routine: Some("_bt_check_unique") }) }', e2e/tests/upgrade-test.rs:623:10
```

**Comment by jgpruitt** [comment]
https://github.com/timescale/promscale_extension/actions/runs/3650480245/jobs/6166520525

```
Run ./install-cargo-pgx.sh
  ./install-cargo-pgx.sh
  shell: /usr/bin/bash -e {0}
  env:
    RUSTC_WRAPPER: sccache
    SCCACHE_BUCKET: promscale-extension-sccache
    AWS_ACCESS_KEY_ID: ***
    AWS_SECRET_ACCESS_KEY: ***
    CARGO_INCREMENTAL: 0
    CARGO_TERM_COLOR: always
    CACHE_ON_FAILURE: false
/home/runner/work/_temp/06f8a33e-d0bd-4aae-95a5-ffff50[2](https://github.com/timescale/promscale_extension/actions/runs/3650480245/jobs/6166520525#step:6:2)61d44.sh: line 1: ./install-cargo-pgx.sh: Permission denied
Error: Process completed with exit code 12[6](https://github.com/timescale/promscale_extension/actions/runs/3650480245/jobs/6166520525#step:6:6).
```

**Comment by jgpruitt** [comment]
https://github.com/timescale/promscale_extension/actions/runs/3650413486/jobs/6166370742

```
---- upgrade_first_no_data_test stdout ----
thread 'upgrade_first_no_data_test' panicked at 'failed to install the extension: Error { kind: Db, cause: Some(DbError { severity: "ERROR", parsed_severity: Some(Error), code: SqlState(E23505), message: "duplicate key value violates unique constraint \"pg_extension_name_index\"", detail: Some("Key (extname)=(promscale) already exists."), hint: None, position: None, where_: None, schema: Some("pg_catalog"), table: Some("pg_extension"), column: None, datatype: None, constraint: Some("pg_extension_name_index"), file: Some("nbtinsert.c"), line: Some(663), routine: Some("_bt_check_unique") }) }', e2e/tests/upgrade-test.rs:623:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
