### ISSUE TITLE
thread '<unnamed>' panicked at 'input time less than lowest time', src/lib.rs:79:17

### ISSUE THREAD

**Issue by nbari** [timescale/promscale_extension#72]
I am using postgres 14 with `promscale 8.0` and `promscale_extension_0.3.0` installed from the source, I started to notice that the node_exporter Grafana dashboard was not reporting the CPU Busy:

<img width="492" alt="Screenshot 2022-01-31 at 14 39 44" src="https://user-images.githubusercontent.com/364199/151803810-10983638-b7f8-4230-bc10-c14170a366e6.png">

After trying to run the query from the grafana and checking the Postgres logs I found this:

```
thread '<unnamed>' panicked at 'input time less than lowest time', src/lib.rs:79:17
time=2022-01-31 13:36:53 UTC, pid=1755480  db=promscale14, usr=promscale, client=timescale-0 , app=promscale@0.8.0, line=19 ERROR:  input time less than lowest time
time=2022-01-31 13:36:53 UTC, pid=1755480  db=promscale14, usr=promscale, client=timescale-0 , app=promscale@0.8.0, line=20 CONTEXT:  <unknown>:0:0
time=2022-01-31 13:36:53 UTC, pid=1755480  db=promscale14, usr=promscale, client=timescale-0 , app=promscale@0.8.0, line=21 STATEMENT:  SELECT series.labels,  result.value_array
                FROM "prom_data_series"."node_cpu_seconds_total" series
                INNER JOIN LATERAL (
                        SELECT prom_rate($7, $8,$9, $10, time, value) as value_array
                        FROM
                        (
                                SELECT time, "value" as value
                                FROM "prom_data"."node_cpu_seconds_total" metric
                                WHERE metric.series_id = series.id
                                AND time >= '2022-01-30T13:31:00Z'
                                AND time <= '2022-01-31T13:36:00Z'
                                ORDER BY time
                        ) as time_ordered_rows
                ) as result ON (result.value_array is not null)
                WHERE
                     labels && (SELECT COALESCE(array_agg(l.id), array[]::int[]) FROM _prom_catalog.label l WHERE l.key = $1 and l.value = $2) AND labels && (SELECT COALESCE(array_agg(l.id), array[]::int[]) FROM _prom_catalog.label l WHERE l.key = $3 and l.value = $4) AND labels && (SELECT COALESCE(array_agg(l.id), array[]::int[]) FROM _prom_catalog.label l WHERE l.key = $5 and l.value = $6)
```
 
How could this be fixed?

**Comment by nbari** [comment]
Hi @JamesGuthrie this is the query I use:

```
(((count(count(node_cpu_seconds_total{instance="$node",job="$job"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance="$node",job="$job"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance="$node",job="$job"}) by (CPU))
```

From the Grafana `Inspect: CPU Busy`
```
{
  "request": {
    "url": "api/datasources/proxy/1/api/v1/query_range",
    "method": "POST",
    "data": {
      "query": "(((count(count(node_cpu_seconds_total{instance=\"10.1.29.160:9100\",job=\"instances\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"10.1.29.160:9100\",job=\"instances\"}[75s])))) * 100) / count(count(node_cpu_seconds_total{instance=\"10.1.29.160:9100\",job=\"instances\"}) by (cpu))",
      "start": 1643551080,
      "end": 1643637480,
      "step": 60
    },
    "hideFromInspector": false
  },
  "response": {
    "status": "error",
    "errorType": "execution",
    "error": "expanding series: appending sample rows: ERROR: input time less than lowest time (SQLSTATE XX000)",
    "message": "expanding series: appending sample rows: ERROR: input time less than lowest time (SQLSTATE XX000)"
  }
}
```

**Comment by nbari** [comment]
This is the grafana dashboard just in case: https://grafana.com/grafana/dashboards/1860

**Comment by JamesGuthrie** [comment]
Hi @nbari, thanks for this bug report! I've just merged https://github.com/timescale/promscale/pull/1098 which fixes this issue. We're releasing a new version of promscale in the next week or so which will contain that fix.
